namespace DndCompanion.Core.Domain.Entities;

/// <summary>
/// A single skill check recorded during a session. The roll is the die result
/// (either generated or physically typed), the modifier is the applied bonus
/// and the difficulty class is the target DC. Total and success are always
/// derived from the raw values so they can never be inconsistent.
/// </summary>
public class SkillCheck : Entity
{
    public Guid SessionId { get; set; }

    /// <summary>Character performing the check, if any.</summary>
    public Guid? CharacterId { get; set; }

    /// <summary>Skill name, e.g. <c>Percezione</c>.</summary>
    public string Skill { get; set; } = string.Empty;

    /// <summary>The die result used for the check.</summary>
    public int Roll { get; set; }

    /// <summary>The bonus applied to the roll.</summary>
    public int Modifier { get; set; }

    /// <summary>The difficulty class the total is compared against.</summary>
    public int DifficultyClass { get; set; }

    /// <summary>True when the DM typed the roll (physical roll) instead of it
    /// being generated by the app.</summary>
    public bool IsPhysicalRoll { get; set; }

    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>Total = roll + modifier.</summary>
    public int Total => Roll + Modifier;

    /// <summary>True when the total meets or beats the difficulty class.</summary>
    public bool IsSuccess => Total >= DifficultyClass;
}